export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_ACTUALUSER_PENDING = 'FETCH_ACTUALUSER_PENDING';
export const FETCH_ACTUALUSER_REJECTED = 'FETCH_ACTUALUSER_REJECTED';
export const FETCH_ACTUALUSER_FULFILLED = 'FETCH_ACTUALUSER_FULFILLED';

export const FETCH_SESSION_PENDING = 'FETCH_SESSION_PENDING';
export const FETCH_SESSION_REJECTED = 'FETCH_SESSION_REJECTED';
export const FETCH_SESSION_FULFILLED = 'FETCH_SESSION_FULFILLED';

export const FETCH_COMPELTESESSION_PENDING = 'FETCH_COMPELTESESSION_PENDING';
export const FETCH_COMPELTESESSION_REJECTED = 'FETCH_COMPELTESESSION_REJECTED';
export const FETCH_COMPLETESESSION_FULFILLED = 'FETCH_COMPLETESESSION_FULFILLED';

export const PUSH_SESSION_PENDING = 'PUSH_SESSION_PENDING';
export const PUSH_SESSION_REJECTED = 'PUSH_SESSION_REJECTED';
export const PUSH_SESSION_FULFILLED = 'PUSH_SESSION_FULFILLED';
export const PUSH_SESSION_COMPLETED = 'PUSH_SESSION_COMPLETED';

export const FETCH_MOVEMENTS_PENDING = 'FETCH_MOVEMENTS_PENDING';
export const FETCH_MOVEMENTS_REJECTED = 'FETCH_MOVEMENTS_REJECTED';
export const FETCH_MOVEMENTS_FULFILLED = 'FETCH_MOVEMENTS_FULFILLED';

export const FETCH_STATS_PENDING = 'FETCH_STATS_PENDING';
export const FETCH_STATS_REJECTED = 'FETCH_STATS_REJECTED';
export const FETCH_STATS_FULFILLED = 'FETCH_STATS_FULFILLED';
